spring.application.name=riskguard
spring.datasource.url=jdbc:postgresql://localhost:5432/riskguard
spring.datasource.username=postgres
spring.datasource.password=C3cili@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=3f8a2b1c9d4e7f0a6b5c2d8e1f4a7b3c9d2e5f8a1b4c7d0e3f6a9b2c5d8e1f4
jwt.expiration=86400000