spring.application.name=riskguard
spring.datasource.url=jdbc:postgresql://localhost:5432/riskguard
spring.datasource.username=postgres
spring.datasource.password=C3cili@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false