spring.application.name=riskguard

# Banco — usa variável de ambiente se existir, senão usa o valor local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/riskguard}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:riskguard_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:riskguard_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.address=0.0.0.0
server.port=8080


# JWT
jwt.secret=${JWT_SECRET:3f8a2b1c9d4e7f0a6b5c2d8e1f4a7b3c9d2e5f8a1b4c7d0e3f6a9b2c5d8e1f4}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Swagger
spring.jpa.open-in-view=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method